name: Build and push image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build the Docker image
      run: |
        docker build . --tag mionita1980/mindit-markdown-compiler:${{steps.date.outputs.date}} --tag mionita1980/mindit-markdown-compiler:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: |
        export CODEQL_VERSION=$(head -n 1 ./codeql.version)
        docker push mionita1980/mindit-markdown-compiler:${{steps.date.outputs.date}}
        docker push mionita1980/mindit-markdown-compiler:latest
